# Generated by Django 5.2.4 on 2025-08-28 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 8, 28, 20, 29, 23, 875972)),
        ),
    ]
